language: node_js
matrix:
  fast_finish: true
  include:
    - node_js: 12
    - node_js: 11
    - node_js: 10
    - node_js: 9
    - node_js: 8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CC="gcc-5";
    export CXX="g++-5";
    export LINK="gcc-5";
    export LINKXX="g++-5";
    fi
script:
  - npm run test #&& exit ${PIPESTATUS[0]}